{"events":[{"defined_class":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues","event":"call","id":173874,"lineno":95,"method_id":"handleDatabaseIssue_dataAccessFailure","path":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java","receiver":{"class":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues","object_id":223428856,"value":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues@d5140f8"},"static":false,"thread_id":1},{"defined_class":"com.example.accesscontrol.exception.GlobalExceptionHandler","event":"call","id":173875,"lineno":72,"method_id":"handleDatabaseConnectionIssue","parameters":[{"class":"org.springframework.dao.DataAccessResourceFailureException","kind":"req","name":"ex","object_id":1442255578,"value":"org.springframework.dao.DataAccessResourceFailureException: db pool exhausted"}],"path":"src/main/java/com/example/accesscontrol/exception/GlobalExceptionHandler.java","receiver":{"class":"com.example.accesscontrol.exception.GlobalExceptionHandler","object_id":1378278940,"value":"com.example.accesscontrol.exception.GlobalExceptionHandler@5226de1c"},"static":false,"thread_id":1},{"elapsed":0.0,"event":"return","id":173876,"parent_id":173875,"return_value":{"class":"org.springframework.http.ResponseEntity","object_id":1759698562,"value":"<503 SERVICE_UNAVAILABLE Service Unavailable,{error=Database connection failed. Please try again later., timestamp=2025-08-18T08:59:36.350967100, status=503},[]>"},"thread_id":1},{"elapsed":1.0081E-4,"event":"return","id":173877,"parent_id":173874,"thread_id":1}],"classMap":[{"children":[{"children":[{"children":[{"children":[{"children":[{"labels":[],"location":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java:95","name":"handleDatabaseIssue_dataAccessFailure","static":false,"type":"function"}],"location":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java","name":"GlobalExceptionHandlerTest$DatabaseIssues","static":false,"type":"class"},{"children":[{"labels":[],"location":"src/main/java/com/example/accesscontrol/exception/GlobalExceptionHandler.java:72","name":"handleDatabaseConnectionIssue","static":false,"type":"function"}],"location":"src/main/java/com/example/accesscontrol/exception/GlobalExceptionHandler.java","name":"GlobalExceptionHandler","static":false,"type":"class"}],"name":"exception","type":"package"}],"name":"accesscontrol","type":"package"}],"name":"example","type":"package"}],"name":"com","type":"package"}],"version":"1.2","metadata":{"name":"Global exception handler $ database issues handle database issue _ data access failure","app":"accesscontrol","language":{"name":"java","version":"17.0.15+6-LTS","engine":"OpenJDK 64-Bit Server VM"},"client":{"name":"appmap-java","url":"https://github.com/appland/appmap-java"},"recorder":{"name":"junit","type":"tests"},"recording":{"defined_class":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues","method_id":"handleDatabaseIssue_dataAccessFailure"},"git":{"repository":"https://github.com/AlhaderMajd/accessControl-majd.git","branch":"main","commit":"76e90bbbe9c01451754b3b84b09fec9d285b5774"},"source_location":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java:95","frameworks":[{"name":"JUnit","version":"5"}],"test_status":"succeeded"},"eventUpdates":{}}