{"events":[{"defined_class":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues","event":"call","id":174255,"lineno":83,"method_id":"handleDatabaseIssue_dataAccessFailure","path":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java","receiver":{"class":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues","object_id":1010932641,"value":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues@3c419ba1"},"static":false,"thread_id":1},{"defined_class":"com.example.accesscontrol.exception.GlobalExceptionHandler","event":"call","id":174256,"lineno":35,"method_id":"handleDatabaseConnectionIssue","parameters":[{"class":"org.springframework.dao.DataAccessResourceFailureException","kind":"req","name":"ex","object_id":1290516798,"value":"org.springframework.dao.DataAccessResourceFailureException: db pool exhausted"}],"path":"src/main/java/com/example/accesscontrol/exception/GlobalExceptionHandler.java","receiver":{"class":"com.example.accesscontrol.exception.GlobalExceptionHandler","object_id":2093465489,"value":"com.example.accesscontrol.exception.GlobalExceptionHandler@7cc7bf91"},"static":false,"thread_id":1},{"elapsed":0.0,"event":"return","id":174257,"parent_id":174256,"return_value":{"class":"org.springframework.http.ResponseEntity","object_id":762484894,"value":"<503 SERVICE_UNAVAILABLE Service Unavailable,{error=Database connection failed. Please try again later., timestamp=2025-08-13T14:42:10.721514500, status=503},[]>"},"thread_id":1},{"elapsed":4.1222E-4,"event":"return","id":174258,"parent_id":174255,"thread_id":1}],"classMap":[{"children":[{"children":[{"children":[{"children":[{"children":[{"labels":[],"location":"src/main/java/com/example/accesscontrol/exception/GlobalExceptionHandler.java:35","name":"handleDatabaseConnectionIssue","static":false,"type":"function"}],"location":"src/main/java/com/example/accesscontrol/exception/GlobalExceptionHandler.java","name":"GlobalExceptionHandler","static":false,"type":"class"},{"children":[{"labels":[],"location":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java:83","name":"handleDatabaseIssue_dataAccessFailure","static":false,"type":"function"}],"location":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java","name":"GlobalExceptionHandlerTest$DatabaseIssues","static":false,"type":"class"}],"name":"exception","type":"package"}],"name":"accesscontrol","type":"package"}],"name":"example","type":"package"}],"name":"com","type":"package"}],"version":"1.2","metadata":{"name":"Global exception handler $ database issues handle database issue _ data access failure","app":"accesscontrol","language":{"name":"java","version":"17.0.15+6-LTS","engine":"OpenJDK 64-Bit Server VM"},"client":{"name":"appmap-java","url":"https://github.com/appland/appmap-java"},"recorder":{"name":"junit","type":"tests"},"recording":{"defined_class":"com.example.accesscontrol.exception.GlobalExceptionHandlerTest$DatabaseIssues","method_id":"handleDatabaseIssue_dataAccessFailure"},"git":{"repository":"https://github.com/AlhaderMajd/accessControl-majd.git","branch":"main","commit":"f969f73139297df67ef2edc2eb60357323900968"},"source_location":"src/test/java/com/example/accesscontrol/exception/GlobalExceptionHandlerTest.java:83","frameworks":[{"name":"JUnit","version":"5"}],"test_status":"succeeded"},"eventUpdates":{}}